version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: TestDB
      POSTGRES_USER: TestUser
      POSTGRES_PASSWORD: TestUserPassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U TestUser -d TestDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/prisma:/app/prisma
    environment:
      DATABASE_URL: postgresql://TestUser:TestUserPassword@db:5432/TestDB

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:8000 
    command: >
      sh -c "npm run dev -- --host 0.0.0.0"

