version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: TestDB
      POSTGRES_USER: TestUser
      POSTGRES_PASSWORD: TestUserPassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U TestUser -d TestDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql://TestUser:TestUserPassword@db:5432/TestDB
  #   command: >
  #     sh -c "prisma generate && 
  #            prisma db push --accept-data-loss &&
  #            uvicorn main:app --reload --host 0.0.0.0 --port 8000"